## Remove URL for GitHub Pages
url: https://jekyll-theme-nixer.michaelnordmeyer.com
title: Jekyll Theme Nixer
description: "An even more barebones theme for Jekyll"

plugins:
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-sitemap

## Jekyll build settings
exclude: [CODE_OF_CONDUCT.md, jekyll-theme-nixer*, LICENSE, Rakefile.rb, README.md]
ignore_theme_config: true # Since Jekyll 4.0, see: https://jekyllrb.com/docs/themes/#pre-configuring-theme-gems40, https://jekyllrb.com/docs/configuration/options/
kramdown:
  show_warnings: true
  syntax_highlighter_opts:
    disable: true
liquid:
  # Configure Liquid’s parser
  error_mode: strict # default: warn
  # Configure Liquid’s renderer
  strict_filters: true # default: false
  # strict_variables: true # default: false
permalink: /:title
sass:
  style: compressed
strict_front_matter: true # default: false
# remote_theme: michaelnordmeyer/jekyll-theme-nixer
# theme: jekyll-theme-nixer
timezone: Europe/Berlin # default: local timezone

## Custom settings used by plugins and the theme
lang: en-US # default: en (is not by Jekyll, but used by many other plugins)
title_separator: • # default: |
## Custom theme settings
favicon: /icon.webp # optional, but mandatory if favicon_dark is used, needs to be 180x180
favicon_dark: /icon-dark.webp # optional, needs to be 180x180
favicon_media_type: image/webp # mandatory, if favicon* is set
theme_settings:
  # error_page_description: "Error page" # default: Error page
  # redirect_page_title: "Redirecting…" # default: Redirecting…
  # redirect_page_description: "Redirect page" # default: 'Redirect page'
  # redirect_page_from: "Redirect from" # default: 'Redirect from'
  # redirect_page_to: "to" # default: 'to'
  # redirect_page_text: "Click here if you are not being redirected." # default: 'Click here if you are not being redirected.'

## https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  - scope:
      path: "" # an empty string here means all files in the project (allows globs, but is slow)
      type: posts # type (optional): posts, pages, drafts, or any collection
    values:
      layout: post
  - scope:
      path: "error"
      type: pages
    values:
      layout: error
      permalink: /:path/:basename
      sitemap: false
