### Remove URL for Github Pages
url: https://jekyll-theme-nixer.michaelnordmeyer.com
title: Jekyll Theme Nixer
description: "An even more barebones theme for Jekyll"

plugins:
  - jekyll-include-cache
  # - jekyll-redirect-from

## Jekyll build settings
exclude: [jekyll-theme-nixer*, LICENSE, Rakefile.rb, README.md]
ignore_theme_config: true # Since Jekyll 4.0, see: https://jekyllrb.com/docs/themes/#pre-configuring-theme-gems40, https://jekyllrb.com/docs/configuration/options/
kramdown:
  show_warnings: true
  syntax_highlighter_opts:
    disable: true
liquid:
  # Configure Liquid’s parser
  error_mode: strict # default: warn
  # Configure Liquid’s renderer
  strict_filters: true # default: false
  # strict_variables: true # default: false
permalink: /:title
sass:
  style: compressed
strict_front_matter: true # default: false
timezone: Europe/Berlin # default: local timezone
# remote_theme: michaelnordmeyer/jekyll-theme-nixer
# theme: jekyll-theme-nixer

## Custom theme settings to not overwrite anything from Jekyll or plugins
lang: en-US # default: en (is not by Jekyll, but used by many other plugins)
theme_settings:
  favicon: /icon.webp # optional, needs to be 180x180
  favicon_dark: /icon-dark.webp # optional, needs to be 180x180
  favicon_media_type: image/webp # mandatory, if favicon is set
  # title_separator: "|" # default: "•"

## https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  - scope:
      path: "" # an empty string here means all files in the project (allows globs, but is slow)
      type: posts # type (optional): posts, pages, drafts, or any collection
    values:
      layout: post
  - scope:
      path: "error"
      type: pages
    values:
      layout: error
      permalink: /:path/:basename
      sitemap: false
