### Remove URL for Github Pages
url: https://jekyll-theme-nixer.michaelnordmeyer.com
icon: /icon.webp
icon_dark: /icon-dark.webp
icon_type: image/webp
title: Jekyll Theme Nixer
description: "An even more barebones theme for Jekyll"

timezone: Europe/Berlin
ignore_theme_config: true
exclude: [jekyll-theme-nixer*, LICENSE, README.md]
date_format: "%Y-%m-%d"

plugins:
  - jekyll-include-cache
  # - jekyll-redirect-from

## Jekyll build settings
kramdown:
  show_warnings: true

permalink: /:title
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
